src/TOURISM.Web/Controllers/DestinationsController.cs
using TOURISM.App.Infrastructure.Utils;
using TOURISM.Web.Utils.Services.Abstracts;
using TOURISM.Web.Controllers.BaseController;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using System;
using TOURISM.App.Models.Enums;
using Newtonsoft.Json;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using X.PagedList;
using TOURISM.App.Models.ViewModels.Public.Content.Outputs;
using System.Reflection;
using TOURISM.Web.Utils.Extensions;
using Microsoft.Extensions.Caching.Memory;
using TOURISM.App.Infraestructure.Utils.Constants;
using System.Collections.Generic;
using System.Data;

namespace TOURISM.Web.Controllers
{
    public class DestinationsController : PublicBaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMemoryCache _memoryCache;
        private readonly MemoryCacheEntryOptions cacheExpiryOptions;
        public DestinationsController(IOptions<AppSettings> settings, IApiClientService apiClient, ILogService logService, ILogger<HomeController> logger, IMemoryCache memoryCache) : base(settings, apiClient, logService)
        {
            _logger = logger;
            _memoryCache = memoryCache;
            cacheExpiryOptions = new MemoryCacheEntryOptions
            {
                AbsoluteExpiration = DateTime.Now.AddSeconds(3600),
                Priority = CacheItemPriority.Normal,
                SlidingExpiration = TimeSpan.FromSeconds(3600)
            };
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var result = await ApiClient.GetBaseContent(InputParameter, AppSettings.SecretKey);

                return View(result);
            }
            catch (Exception ex)
            {
                return await Error(EErrorCodeClientApi.HomeController, ex);
            }
        }

        public async Task<IActionResult> Detail([FromQuery] string destination)
        {
            try
            {
                var input = InputParameter;
                input.ItemClass = string.Concat(AppSettings.OntologyPrefix, destination);

                var cacheKey = $"{CacheKeyConstants.OntologyClass}_{destination}";
                if (!_memoryCache.TryGetValue(cacheKey, out List<OntologyDTO> result))
                {
                    result = await ApiClient.GetClassContent(input, AppSettings.SecretKey);
                    if (result.Count > 1)
                        result = result.Where(row => row.Class == input.ItemClass).ToList();

                    foreach(var item in result)
                    {
                        foreach(var ind in item.Individuals)
                        {
                            ind.ValueList = string.Join(",", (ind.Properties.Where(row => row.Axioms != null)
                                .SelectMany(row => row.Axioms).Where(row => row.Values != null)
                                    .SelectMany(r => r.Values)
                                        .Select(row => row.Value.ReplaceOntology())).ToList());

                        }
                    }
                    
                    _memoryCache.Set(cacheKey, result, cacheExpiryOptions);
                }

                return View(result);
            }
            catch (Exception ex)
            {
                return await Error(EErrorCodeClientApi.DestinationController, ex);
            }
        }

        public async Task<IActionResult> DestinationDetail([FromQuery] string type, string destination, string city)
        {
            try
            {
                var input = InputParameter;
                input.ItemClass = string.Concat(AppSettings.OntologyPrefix, destination);
                input.Individual = string.Concat(AppSettings.OntologyPrefix, city.Replace(" ", "_"));
                var result = await ApiClient.GetClassContent(input, AppSettings.SecretKey);

                var output = result.Where(row => row.Class == input.ItemClass).ToList();
                return View(output);
            }
            catch (Exception ex)
            {
                return await Error(EErrorCodeClientApi.AccommodationController, ex);
            }
        }
    }
}

src/TOURISM.Web/Views/Shared/Partials/_Error.cshtml
@model EErrorCodeClientApi;

@{
    ViewData["Title"] = ViewBag.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="hero page-inner overlay" style="background-image: url('@string.Concat(settings.Value.BaseUrl, "images/Home/Top/error.jpg")')">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-9 text-center mt-5">
                <h1 class="heading" data-aos="fade-up">
                    @Lang("_ErrorPage")
                </h1>

                <nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="200">
                    <ol class="breadcrumb text-center justify-content-center">
                        <li class="breadcrumb-item"><a href="index.html">@Lang("_Home")</a></li>
                        <li class="breadcrumb-item" style="color:#fff;">Error</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-lg-12">
                <h1>@Lang("_ErrorPage")</h1>
                @Lang("_Global_ServerError")
                <div class="text-center">
                    @Lang("_Global_ServerError_ReferenceCode"): @(((int)Model).ToString("D8"))
                </div>
            </div>
        </div>
    </div>
</div>

src/TOURISM.Web/Views/Shared/Partials/_Error404.cshtml
@model EErrorCodeClientApi;

@{
    ViewData["Title"] = ViewBag.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="hero page-inner overlay" style="background-image: url('@string.Concat(settings.Value.BaseUrl, "images/Home/Top/error.jpg")')">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-9 text-center mt-5">
                <h1 class="heading" data-aos="fade-up">
                    404 - @Lang("_Notfound")
                </h1>

                <nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="200">
                    <ol class="breadcrumb text-center justify-content-center">
                        <li class="breadcrumb-item"><a href="index.html">@Lang("_Home")</a></li>
                        <li class="breadcrumb-item" style="color:#fff;">Error</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-lg-12">
                <div class="text-center">
                    <img src="~/images/icons/code-error.png" class="img-fluid text-center" />
                </div>
                <h1>@Lang("_Notfound")</h1>
                <br />
                <span class="font-weight-bold">@Lang("_Global_PageNoFound")</span>
                <div class="text-center">
                    @Lang("_Global_ServerError_ReferenceCode"): <span class="font-weight-bold">@(((int)Model).ToString("D8"))</span>
                </div>
            </div>
        </div>
    </div>
</div>

src/TOURISM.Web/Views/Shared/Partials/_Footer.cshtml
<div class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <p>
          @Lang("_CopyRight") &copy; @DateTime.Now.Year - @Lang("_RightsReserved")
        </p>
      </div>
    </div>
  </div>
</div>

src/TOURISM.Web/Views/Shared/Partials/_Nav.cshtml
@{
    var language = (string)ViewBag.CultureTwoLetterName;
    var languageName = language == "ES" ? Lang("_English") : Lang("_Spanish");
    var newLanguage = language == "ES" ? "EN" : "ES";

    //Move to show from service
    var destinationItems = new List<string>()
    {
        "Beach",
        "CulturalAreas",
        "NaturalAreas",
        "TownAndCities",
        "WinterSportAreas"
    };
}

<nav class="site-nav">
    <div class="container">
        <div class="menu-bg-wrap">
            <div class="site-navigation">
                <a asp-controller="Home" asp-action="Index" class="logo m-0 float-start">@Lang("_Tourism")</a>
                <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                    <li class="active"><a asp-controller="Home" asp-action="Index">@Lang("_Home")</a></li>
                    <li class="has-children">
                        <a asp-controller="Destinations" asp-action="Index">@Lang("_Destinations")</a>
                        <ul class="dropdown">
                            @foreach(var item in destinationItems)
                            {
                                <li><a asp-controller="Destinations" asp-action="Detail" asp-route-destination="@item" class="loading">@Lang(string.Concat("_", item))</a></li>
                            }
                        </ul>
                    </li>
                    <li><a asp-controller="Home" asp-action="Ontology">@Lang("_Ontology")</a></li>
                    <li><a target="_blank" href="@string.Concat(settings.Value.BaseUrl, settings.Value.DocumentationFile.Url, "?v=", settings.Value.DocumentationFile.Version)">@Lang("_Paper")</a></li>
                    <li class="language-container">
                        <a class="change-lang" href="#" value="@newLanguage">@languageName</a>
                    </li>
                </ul>
                <a href="#" class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none" data-toggle="collapse" data-target="#main-navbar">
                    <span></span>
                </a>
            </div>
        </div>
    </div>
</nav>

@Html.Script(@<script type="text/javascript">
            $('.language-container .change-lang').on('click', function(e) {
                var lang = $(this).attr('value');
                if (lang !== '') {
                    e.preventDefault();
                    TourismApp.Ajax.Post('@Url.Action("ChangeLanguage", "Home")', { returnUrl: '@Context.Request.GetEncodedUrl()', newLang: lang },
                        function(datos) {
                            window.location.href = datos.targetUrl.url;
                        },
                        function(datos) { }
                    )
                }
            });
    </script>)

src/TOURISM.Web/Views/Shared/Partials/_TopHeader.cshtml
@model TopHeaderDTO

<div class="hero page-inner overlay" style="background-image: url('@string.Concat(settings.Value.BaseUrl, Model.Image)')">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-9 text-center mt-5">
                <h1 class="heading" data-aos="fade-up">
                    @Model.AdditionalText
                </h1>
                <nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="200">
                    <ol class="breadcrumb text-center justify-content-center">
                        @foreach (var item in Model.BreadCrumb.OrderBy(row => row.Order).ToList())
                        {
                            if (!string.IsNullOrWhiteSpace(item.Action))
                            {
                                <li class="breadcrumb-item"><a href="@item.Action">@item.Text</a></li>
                            }
                            else
                            {
                                <li class="breadcrumb-item active text-white-50" aria-current="page">@item.Text</li>
                            }
                        }
                    </ol>
                </nav>
            </div>
            @if (Model.ShowSearch)
            {
                <div class="col-lg-7 col-sm-12 text-center" style="margin-top:-12rem;">
                    <div class="mb-3">
                        <input type="text" v-model="search.new" class="form-control px-4" placeholder="@Lang("_SearchPlaceholder1")" style="border-radius: 25px;">
                    </div>
                </div>
            }
        </div>
    </div>
</div>